language:
    csharp
sudo: required
mono: none 
dotnet: 3.0

os:
  - linux

global:
- DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
- DOTNET_CLI_TELEMETRY_OPTOUT=true
   
    
 jobs:
  include:
    - stage: restore
      script: .scripts/restore.sh

    - stage: build
      script: .scripts/build.sh

    - stage: test
          script: .scripts/test.sh

    - stage: push-package
      if: branch = master AND type = push
      script: .scripts/push.sh
        