language:
    csharp
sudo: required
mono: none 
dotnet: 3.0

os:
  - linux

global:
- DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
- DOTNET_CLI_TELEMETRY_OPTOUT=true
   
    
jobs:
  include:
    - stage: restore
      script: 
        - dotnet restore ./Dramarr.Core/Dramarr.Core.csproj
        - dotnet restore ./Dramarr.Core.Tests/Dramarr.Core.Tests.csproj

    - stage: build
      script:
        - dotnet build ./Dramarr.Core/Dramarr.Core.csproj --configuration Release

    - stage: test
          script:
            - dotnet test ./Dramarr.Core/Dramarr.Core.csproj --configuration Release

    - stage: push-package
      if: branch = master AND type = push
      script:
        - dotnet nuget push ./Dramarr.Core/bin/Release/*.nupkg -k $NUGET_API_KEY  -s "https://nuget.org"
        - dotnet nuget push ./Dramarr.Core/bin/Release/*.nupkg -k $GITHUB_API_KEY -s "https://nuget.pkg.github.com/Dramarr/index.json"