language:
    csharp
sudo: required
mono: none 
dotnet: 3.0

os:
  - linux

global:
- DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
- DOTNET_CLI_TELEMETRY_OPTOUT=true


before_script:
    - dotnet restore ./Dramarr.Core/Dramarr.Core.csproj
    - dotnet restore ./Dramarr.Core.Tests/Dramarr.Core.Tests.csproj
    
  
script:
    - dotnet build ./Dramarr.Core/Dramarr.Core.csproj --configuration Release
    - dotnet test ./Dramarr.Core.Tests/Dramarr.Core.Tests.csproj --configuration Release