language:
    csharp
sudo: required
mono: none 
dotnet: 3.0

os:
  - linux

global:
- DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
- DOTNET_CLI_TELEMETRY_OPTOUT=true
   
jobs:
  include:
    - stage: restore
      script: bash scripts/restore.sh

    - stage: build
      script: bash scripts/build.sh

    - stage: test
      script: bash scripts/test.sh

    - stage: push-package
      if: branch = master AND type = push
      script: bash scripts/push.sh
        